#!/usr/bin/env node
process.env.NODE_ENV = 'test';

const logger = console;

const config = require('config');
const AWS = require('../src/utils/aws');

const provision = async () => {
    const s3 = new AWS.S3();
    await s3.createBucket({
        Bucket: config.awsBucket
    }).promise();
};

const main = async () => {
  try {
      logger.info("Provisioning localstack", AWS.config.endpoint);
      await provision();
      logger.info("Ready");
  } catch(e) {
      logger.error(e);
      process.exit(1);
  }
};

main();
